### ISSUE TITLE
The HeadBucket operation requires non-empty parameter: Bucket

### ISSUE THREAD

**Issue by AdamBark** [catalyst/mahara-module_objectfs#15]
I installed this module and the AWS module but I get the following error when opening the "Plugin Administration"

[WAR] d5 (lib/errors.php:529) [InvalidArgumentException]: The HeadBucket operation requires non-empty parameter: Bucket at /var/www/html/module/aws/sdk/Aws/InputValidationMiddleware.php:64

Is there extra configuration required other than what is mentioned in the README?

**Comment by jsmith20231** [comment]
This appears to be an issue with the configuration page not creating the s3_bucket field when it loads. It requires a value or you'll get the above error. As a workaround this field can be added manually via a query to the database, after which the page should load and allow you to configure the other settings needed:
`insert into module_config (plugin,field,value) values ('objectfs','s3_bucket','<your_bucket_name>');`

**Comment by AdamBark** [comment]
Thanks, that workaround seems to resolve the issue.
