### ISSUE TITLE
Images are not resized

### ISSUE THREAD

**Issue by djarran** [catalyst/mahara-module_objectfs#17]
**Description:**
When visiting the `/artefact/file/index.php` page, images retrieved from remote storage (S3) are full size. These images should be resized to 25x25 pixels - thumbnail size within the file list browser. 

**Screenshot:**
![image](https://github.com/catalyst/mahara-module_objectfs/assets/65814885/617b5253-75ef-49d3-becd-a06c4bb8149f)

**Comment by anitsirk** [comment]
You will also need the [Mahara patch](https://git.mahara.org/catalyst/mahara/-/issues/495.

**Comment by golenkovm** [comment]
Closing this as fixed
